/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRisksRouteImport } from './routes/_app.risks'
import { Route as AppReviewsRouteImport } from './routes/_app.reviews'
import { Route as AppOkrsRouteImport } from './routes/_app.okrs'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppKpiRouteImport } from './routes/_app.kpi'
import { Route as AppExperienceRouteImport } from './routes/_app.experience'
import { Route as AppDecisionsRouteImport } from './routes/_app.decisions'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoachesRouteImport } from './routes/_app.coaches'
import { Route as AppChallengesRouteImport } from './routes/_app.challenges'
import { Route as AppBoardRouteImport } from './routes/_app.board'
import { Route as AppAssessmentRouteImport } from './routes/_app.assessment'
import { Route as AppActionPlansRouteImport } from './routes/_app.action-plans'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as ApiPublicDemoChatRouteImport } from './routes/api/public.demo-chat'
import { Route as AppChatThreadIdRouteImport } from './routes/_app.chat.$threadId'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRisksRoute = AppRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppOkrsRoute = AppOkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiRoute = AppKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AppRoute,
} as any)
const AppExperienceRoute = AppExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachesRoute = AppCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentRoute = AppAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppActionPlansRoute = AppActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicDemoChatRoute = ApiPublicDemoChatRouteImport.update({
  id: '/api/public/demo-chat',
  path: '/api/public/demo-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/try': typeof TryRoute
  '/action-plans': typeof AppActionPlansRoute
  '/assessment': typeof AppAssessmentRoute
  '/board': typeof AppBoardRoute
  '/challenges': typeof AppChallengesRoute
  '/coaches': typeof AppCoachesRoute
  '/dashboard': typeof AppDashboardRoute
  '/decisions': typeof AppDecisionsRoute
  '/experience': typeof AppExperienceRoute
  '/kpi': typeof AppKpiRoute
  '/lessons': typeof AppLessonsRoute
  '/notes': typeof AppNotesRoute
  '/okrs': typeof AppOkrsRoute
  '/reviews': typeof AppReviewsRoute
  '/risks': typeof AppRisksRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/try': typeof TryRoute
  '/action-plans': typeof AppActionPlansRoute
  '/assessment': typeof AppAssessmentRoute
  '/board': typeof AppBoardRoute
  '/challenges': typeof AppChallengesRoute
  '/coaches': typeof AppCoachesRoute
  '/dashboard': typeof AppDashboardRoute
  '/decisions': typeof AppDecisionsRoute
  '/experience': typeof AppExperienceRoute
  '/kpi': typeof AppKpiRoute
  '/lessons': typeof AppLessonsRoute
  '/notes': typeof AppNotesRoute
  '/okrs': typeof AppOkrsRoute
  '/reviews': typeof AppReviewsRoute
  '/risks': typeof AppRisksRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AppChatThreadIdRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/try': typeof TryRoute
  '/_app/action-plans': typeof AppActionPlansRoute
  '/_app/assessment': typeof AppAssessmentRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/challenges': typeof AppChallengesRoute
  '/_app/coaches': typeof AppCoachesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/decisions': typeof AppDecisionsRoute
  '/_app/experience': typeof AppExperienceRoute
  '/_app/kpi': typeof AppKpiRoute
  '/_app/lessons': typeof AppLessonsRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/okrs': typeof AppOkrsRoute
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/risks': typeof AppRisksRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/chat/$threadId': typeof AppChatThreadIdRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/_app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/try'
    | '/action-plans'
    | '/assessment'
    | '/board'
    | '/challenges'
    | '/coaches'
    | '/dashboard'
    | '/decisions'
    | '/experience'
    | '/kpi'
    | '/lessons'
    | '/notes'
    | '/okrs'
    | '/reviews'
    | '/risks'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/demo-chat'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/try'
    | '/action-plans'
    | '/assessment'
    | '/board'
    | '/challenges'
    | '/coaches'
    | '/dashboard'
    | '/decisions'
    | '/experience'
    | '/kpi'
    | '/lessons'
    | '/notes'
    | '/okrs'
    | '/reviews'
    | '/risks'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/demo-chat'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/try'
    | '/_app/action-plans'
    | '/_app/assessment'
    | '/_app/board'
    | '/_app/challenges'
    | '/_app/coaches'
    | '/_app/dashboard'
    | '/_app/decisions'
    | '/_app/experience'
    | '/_app/kpi'
    | '/_app/lessons'
    | '/_app/notes'
    | '/_app/okrs'
    | '/_app/reviews'
    | '/_app/risks'
    | '/_app/settings'
    | '/api/chat'
    | '/_app/chat/$threadId'
    | '/api/public/demo-chat'
    | '/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  TryRoute: typeof TryRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicDemoChatRoute: typeof ApiPublicDemoChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risks': {
      id: '/_app/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof AppRisksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/okrs': {
      id: '/_app/okrs'
      path: '/okrs'
      fullPath: '/okrs'
      preLoaderRoute: typeof AppOkrsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpi': {
      id: '/_app/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AppKpiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experience': {
      id: '/_app/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof AppExperienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coaches': {
      id: '/_app/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof AppCoachesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges': {
      id: '/_app/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment': {
      id: '/_app/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AppAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-plans': {
      id: '/_app/action-plans'
      path: '/action-plans'
      fullPath: '/action-plans'
      preLoaderRoute: typeof AppActionPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/demo-chat': {
      id: '/api/public/demo-chat'
      path: '/api/public/demo-chat'
      fullPath: '/api/public/demo-chat'
      preLoaderRoute: typeof ApiPublicDemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/$threadId': {
      id: '/_app/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionPlansRoute: typeof AppActionPlansRoute
  AppAssessmentRoute: typeof AppAssessmentRoute
  AppBoardRoute: typeof AppBoardRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppCoachesRoute: typeof AppCoachesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppExperienceRoute: typeof AppExperienceRoute
  AppKpiRoute: typeof AppKpiRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppOkrsRoute: typeof AppOkrsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppRisksRoute: typeof AppRisksRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionPlansRoute: AppActionPlansRoute,
  AppAssessmentRoute: AppAssessmentRoute,
  AppBoardRoute: AppBoardRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppCoachesRoute: AppCoachesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppExperienceRoute: AppExperienceRoute,
  AppKpiRoute: AppKpiRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppNotesRoute: AppNotesRoute,
  AppOkrsRoute: AppOkrsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppRisksRoute: AppRisksRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppChatThreadIdRoute: AppChatThreadIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  TryRoute: TryRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicDemoChatRoute: ApiPublicDemoChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
